import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { StrictMode } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full font-raleway">
      <body className="min-h-screen flex flex-col">
        <StrictMode>
          <Navbar />
          <main className="flex-1">{children}</main>
        </StrictMode>
      </body>
    </html>
  );
}
