import type { Metadata } from "next";
import "./globals.css";
import { StrictMode } from "react";
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Pakistan Red Crescent Society | Logistics Management System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full font-raleway">
      <body className="h-full">
        <Navbar />
        <StrictMode>{children}</StrictMode>
      </body>
    </html>
  );
}
